# Site settings
title: "Valaistuneet.fi"
author: "Artanicus"
description:
  "Community front for ENL Finland"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://beta.valaistuneet.fi" # the base hostname & protocol for your site
source-url: "https://github.com/artanicus/artanicus.github.io/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      category: "spells"
